---
title: "Untitled"
author: "girl squad"
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: yes
    toc: yes
    theme: cosmo
    toc_float: yes
    code_folding: hide
    number_sections: no
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
p_load(dplyr, ggplot2, sf, stats, tidycensus, tidyr, mapview, tigris, tmap)
```

```{r geography, include=FALSE, message=FALSE, warning=FALSE}

options(tigris_use_cache = TRUE)

md_bound <- counties(state = "MD") %>%
  st_transform("EPSG:4269") %>%
  erase_water(area_threshold = 0.9)

water_bound <- st_as_sfc(st_bbox(md_bound), crs = "EPSG:4269")

```

```{r callingacsdata, include=FALSE, message=FALSE, warning=FALSE}
#Getting my ACS Variable LIst
acs_variable_list.2012 <- load_variables(2012, 
                                         "acs5", 
                                         cache = TRUE)

#Picking out my variables of interest
acs_vars <- c("B01001_001E",# ACS total Pop estimate
          "B25002_001E",# Estimate of total housing units
          "B25002_003E",# Number of vacant housing units
          "B19013_001E",# Median HH Income ($)
          "B02001_002E",# People describing themselves as "white alone"
          "B06009_006E", # Total graduate or professional degree
          "B07001_033E", #moved in within same county
          "B07001_049E", #moved in from same state
          "B07001_065E", #moved in different state
          "B07001_081E", #moved from abroad
          "B06009_005E", #bachelors degree
          "B25010_002E", #owner occupied household size
          "B25010_003E", #renter occupied HH size
          "B11016_002E", #family households
          "B11016_009E", #non family households
          "B25064_001E", #MEDIAN GROSS RENT
          "B25077_001E") #MEDIAN HOME VALUE

#Extracting the data for 2012
bmore_acs12 <- get_acs(
  geography = "tract", 
  variables = acs_vars,
  state = "MD", 
  county = "Baltimore City",
  year = 2012,
  output = "wide")%>%
  rename(TotalPopulation12 = B01001_001E,
      TotalHousingUnits12 = B25002_001E,
      VacantHousingUnits12 = B25002_003E,
      MedianHouseholdIncome12 = B19013_001E,
      WhiteAlone12 = B02001_002E,
      GradProfessionalDegree12 = B06009_006E,
      MovedWithinCounty12 = B07001_033E,
      MovedFromSameState12 = B07001_049E,
      MovedFromDifferentState12 = B07001_065E,
      MovedAbroad12 = B07001_081E,
      BachelorsDegree12 = B06009_005E,
      OwnerOccupiedHouseholdSize12 = B25010_002E,
      RenterOccupiedSize12 = B25010_003E,
      FamilyHouseholds12 = B11016_002E,
      NonFamilyHouseholds12 = B11016_009E,
      MedianRent12 = B25064_001E,
      MedianHomeValue12 = B25077_001E)%>%
  mutate(inflation.adjHH12 = MedianHouseholdIncome12 * 1.24)%>%
  select(GEOID,NAME,ends_with("12"))

#extracting my data for 2022
bmore_acs22 <- get_acs(
  geography = "tract", 
  variables = acs_vars,
  state = "MD", 
  county = "Baltimore City",
  year = 2022,
  output = "wide")%>%
  rename(TotalPopulation22 = B01001_001E,
      TotalHousingUnits22 = B25002_001E,
      VacantHousingUnits22 = B25002_003E,
      MedianHouseholdIncome22 = B19013_001E,
      WhiteAlone22 = B02001_002E,
      GradProfessionalDegree22 = B06009_006E,
      MovedWithinCounty22 = B07001_033E,
      MovedFromSameState22 = B07001_049E,
      MovedFromDifferentState22 = B07001_065E,
      MovedAbroad22 = B07001_081E,
      BachelorsDegree22 = B06009_005E,
      OwnerOccupiedHouseholdSize22 = B25010_002E,
      RenterOccupiedSize22 = B25010_003E,
      FamilyHouseholds22 = B11016_002E,
      NonFamilyHouseholds22 = B11016_009E,
      MedianRent22 = B25064_001E,
      MedianHomeValue22 = B25077_001E)%>%
  select(GEOID,NAME,ends_with("22"))

#one census tract has been combined in 2022. So I am adjusting this info in 2012 and joining back
changed_22 <- bmore_acs12 %>%
  filter(NAME %in% c("Census Tract 1801, Baltimore city, Maryland", 
                     "Census Tract 1802, Baltimore city, Maryland"))%>%
  dplyr::summarize(
    TotalPopulation12 = sum(TotalPopulation12),
    TotalHousingUnits12 = sum(TotalHousingUnits12),
    VacantHousingUnits12 = sum(VacantHousingUnits12),
    MedianHouseholdIncome12 = mean(MedianHouseholdIncome12),
    WhiteAlone12 = sum(WhiteAlone12),
    GradProfessionalDegree12 = sum(GradProfessionalDegree12),
    MovedWithinCounty12 = sum(MovedWithinCounty12),
    MovedFromSameState12 = sum(MovedFromSameState12),
    MovedFromDifferentState12 = sum(MovedFromDifferentState12),
    MovedAbroad12 = sum(MovedAbroad12),
    BachelorsDegree12 = sum(BachelorsDegree12),
    OwnerOccupiedHouseholdSize12 = mean(OwnerOccupiedHouseholdSize12),
    RenterOccupiedSize12 = mean(RenterOccupiedSize12),
    FamilyHouseholds12 = sum(FamilyHouseholds12),
    NonFamilyHouseholds12 = sum(NonFamilyHouseholds12),
    inflation.adjHH12 = mean(inflation.adjHH12),
    MedianRent12 = mean(MedianRent12),
    MedianHomeValue12 = mean(MedianRent12)
  ) %>%
  dplyr::mutate(
    NAME = "Census Tract 2806, Baltimore city, Maryland",
    GEOID = "24510280600"
  )

#joining back adjusted info
bmore_acs12 <- bmore_acs12 %>%
  filter(!(NAME %in% c("Census Tract 1801, Baltimore city, Maryland", 
                       "Census Tract 1802, Baltimore city, Maryland"))) %>%
  bind_rows(changed_22)

#creating large dataset
all.acs <- bmore_acs12 %>%
  left_join(bmore_acs22, by = c("GEOID"))%>%
  mutate(
    HHIncChangeper = ((MedianHouseholdIncome22 - MedianHouseholdIncome12) / MedianHouseholdIncome12) * 100
  )%>%
  mutate(NAME = coalesce(NAME.x, NAME.y)) %>% 
  select(-NAME.x, -NAME.y) 
```

Now we are working on getting our gentrification index. First, we want to calculate the percentage of low and high income people for census tracts in both years.

```{r callingincomedata}
#Getting population by Income numbers
bmore_ctmedhhinc12 <- get_acs(
  geography = "tract", 
  variables = c(tot = "B19001_001", 
                L = "B19001_002", L = "B19001_003", L = "B19001_004", L = "B19001_005", L = "B19001_006",
                H = "B19001_007", H = "B19001_008", H = "B19001_009", H = "B19001_010", H = "B19001_011", 
                H = "B19001_012", H = "B19001_013", H = "B19001_014", H = "B19001_015", H = "B19001_016", 
                H = "B19001_017"),
  state = "MD", 
  county = "Baltimore City",
  year = 2012,
  geometry = FALSE 
) %>%
  select(GEOID, variable, estimate) %>%
  rename(est12 = estimate, var12 = variable) %>%
  group_by(GEOID, var12) %>%
  summarise(est12 = sum(est12)) %>%
  pivot_wider(names_from = var12, values_from = est12) %>%
  mutate(percentHighInc12 = H/tot, percentLowInc12 = L/tot)

#adjusting for joined census tracts
changed_22Inc <- bmore_ctmedhhinc12 %>%
  filter(GEOID %in% c("24510180100", "24510180200")) %>%
  ungroup() %>%
  summarize(H = sum(H), L = sum(L), tot = sum(tot)) %>%
  mutate(percentHighInc12 = H / tot,
         percentLowInc12 = L / tot) %>%
  mutate(GEOID = "24510280600")

#joining info back to 2012
bmore_ctmedhhinc12 <- bmore_ctmedhhinc12 %>%
  ungroup()%>%
  filter(!(GEOID %in% c("24510180100", "24510180200"))) %>%
  bind_rows(changed_22Inc)

#getting HH income for 2022
bmore_ctmedhhinc22 <- get_acs(
  geography = "tract", 
  variables = c(tot = "B19001_001", 
                L = "B19001_002", L = "B19001_003", L = "B19001_004", L = "B19001_005", L = "B19001_006",
                L = "B19001_007", L = "B19001_008", L = "B19001_009", H = "B19001_010", H = "B19001_011", 
                H = "B19001_012", H = "B19001_013", H = "B19001_014", H = "B19001_015", H = "B19001_016", 
                H = "B19001_017"),
  state = "MD", 
  county = "Baltimore City",
  year = 2022,
  geometry = FALSE 
) %>%
  select(GEOID, variable, estimate) %>%
  rename(est22 = estimate, var22 = variable) %>%
  group_by(GEOID, var22) %>%
  summarise(est22 = sum(est22)) %>%
  pivot_wider(names_from = var22, values_from = est22) %>%
  mutate(percentHighInc22 = H/tot, percentLowInc22 = L/tot)
```
Now that the data is ready getting it in my index

```{r makingindex}
#joining all
bmore_hhinc_change <- left_join(bmore_ctmedhhinc12, bmore_ctmedhhinc22, by = "GEOID") %>%
  select(GEOID, percentHighInc12, percentHighInc22, percentLowInc12, percentLowInc22)

#creating my final dataset
all.acs <- left_join(all.acs, bmore_hhinc_change)%>%
  mutate(ChangeInHighIncPct = (percentHighInc22 - percentHighInc12),
         ChangeInLowIncPct = (percentLowInc22 - percentLowInc12))

#getting my index
all.acs <- all.acs %>%
  mutate(
    NHHIncChangeper = HHIncChangeper / max(abs(HHIncChangeper), na.rm = TRUE),
    NChangeInHighIncPct = ChangeInHighIncPct / max(abs(ChangeInHighIncPct), na.rm = TRUE),
    NChangeInLowIncPct = ChangeInLowIncPct / max(abs(ChangeInLowIncPct), na.rm = TRUE)
  )%>%
  mutate(genindex = NChangeInHighIncPct - (NChangeInLowIncPct))%>%
  mutate(gentrify = case_when((genindex > (quantile(all.acs$genindex, 0.75, na.rm = TRUE)))~ 1,
         TRUE ~ 0))
```
Now joining to Shape file

```{r joiningviz1}
baltimore_tracts <- tracts(state = "MD", county = "Baltimore City", year = 2022)
all.acs.sf <- left_join(baltimore_tracts, all.acs, by = "GEOID")

tm_shape(all.acs.sf)+
  tm_polygons(fill = "gentrify")
```



```{r bmore_data, message=FALSE, warning=FALSE}
#Vacant lots 
bmore_lots <- st_read("https://egisdata.baltimorecity.gov/egis/rest/services/Housing/DHCD_Open_Baltimore_Datasets/FeatureServer/1/query?outFields=*&where=1%3D1&f=geojson")

bmore_lots$DateNotice <- as.POSIXct(bmore_lots$DateNotice, format = "%Y-%m-%d %H:%M:%S")

#Open-Bid List - Vacants to Value 
bmore_bids <- st_read("https://egisdata.baltimorecity.gov/egis/rest/services/Housing/DHCD_Open_Baltimore_Datasets/FeatureServer/7/query?outFields=*&where=1%3D1&f=geojson")

#Universities & colleges? 
bmore_colleges <- st_read("https://services1.arcgis.com/UWYHeuuJISiGmgXx/arcgis/rest/services/Universities_and_Colleges/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson")

#Businesses by community statistical areas 
bmore_business <- st_read("https://services1.arcgis.com/mVFRs7NF4iFitgbY/arcgis/rest/services/Neiind/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson")
 
#Percentage of vacant lots 
bmore_p_lots <- st_read("https://services1.arcgis.com/mVFRs7NF4iFitgbY/arcgis/rest/services/Vacant/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson")


#Note to self (Tina) - make new combined features file 


#Baltimore schools

school_outcome <- st_read("https://services1.arcgis.com/mVFRs7NF4iFitgbY/arcgis/rest/services/Pread3/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson")

```

## Visualization

```{r bmorevis_data, message=FALSE, warning=FALSE}

#2022 Median Household Income
bmore_hhinc22 <- get_acs(
  geography = "tract", 
  variables = "B19013_001",
  state = "MD", 
  county = "Baltimore City",
  year = 2022,
  geometry = TRUE 
) %>%
  select(GEOID, estimate)

#2022 Majority Non-White
bmore_nonwhite22 <- get_acs(
  geography = "tract", 
  variables = c(tot = "B03002_001", white = "B03002_003"),
  state = "MD", 
  county = "Baltimore City",
  year = 2022,
  geometry = TRUE
) %>%
  select(GEOID, variable, estimate) %>%
  pivot_wider(names_from = variable, values_from = estimate) %>%
  mutate(nonwhite = 1 - (white/tot))

#2022 Majority Owner
bmore_pcentoo22 <- get_acs(
  geography = "tract", 
  variables = c(tot = "B25003_001", oo = "B25003_002", ro = "B25003_003"),
  state = "MD", 
  county = "Baltimore City",
  year = 2022,
  geometry = TRUE
) %>%
  select(GEOID, variable, estimate) %>%
  pivot_wider(names_from = variable, values_from = estimate) %>%
  mutate(propoo = (oo/tot))

#2022 Median Home Value
bmore_hv22 <- get_acs(
  geography = "tract", 
  variables = "B25077_001",
  state = "MD", 
  county = "Baltimore City",
  year = 2022,
  geometry = TRUE 
) %>%
  select(GEOID, estimate)

#2022 Median Rent


```

```{r bmorevis_map, message=FALSE, warning=FALSE}
 
#2022 Median Household Income
ggplot() +
  geom_sf(data = water_bound, fill = "steelblue") +
  geom_sf(data = md_bound, fill = "gray80", col = "gray75") +
  geom_sf(data = bmore_hhinc22, aes(fill = estimate), col = "transparent") +
  scale_fill_gradient(
    high = "orangered4",
    low = "lightgoldenrod1",
    labels = scales::dollar) +
  theme_void() +
  xlim(-76.75, -76.48) +
  ylim(39.2, 39.38) +
  theme(legend.position = "bottom", legend.key.width = unit(1.5, "cm")) +
  labs(fill = "Median Household Income",
       title = "2022 Median Household Income",
       subtitle = "Baltimore City, MD")

#2022 Majority Non-White
ggplot() +
  geom_sf(data = water_bound, fill = "steelblue") +
  geom_sf(data = md_bound, fill = "gray80", col = "gray75") +
  geom_sf(data = bmore_nonwhite22, aes(fill = nonwhite), col = "transparent") +
  scale_fill_gradient(
    high = "orangered4",
    low = "lightgoldenrod1",
    labels = scales::percent) +
  theme_void() +
  xlim(-76.75, -76.48) +
  ylim(39.2, 39.38) +
  theme(legend.position = "bottom", legend.key.width = unit(1.5, "cm")) +
  labs(fill = "Percent Non-White",
       title = "2022 Race/Ethnicity",
       subtitle = "Baltimore City, MD")

#2022 Majority Owner
ggplot() +
  geom_sf(data = water_bound, fill = "steelblue") +
  geom_sf(data = md_bound, fill = "gray80", col = "gray75") +
  geom_sf(data = bmore_pcentoo22, aes(fill = propoo), col = "transparent") +
  scale_fill_gradient(
    high = "orangered4",
    low = "lightgoldenrod1",
    labels = scales::percent) +
  theme_void() +
  xlim(-76.75, -76.48) +
  ylim(39.2, 39.38) +
  theme(legend.position = "bottom", legend.key.width = unit(1.5, "cm")) +
  labs(fill = "Percent Owner-Occupied",
       title = "2022 Tenure",
       subtitle = "Baltimore City, MD")

#2022 Median Home Value
ggplot() +
  geom_sf(data = water_bound, fill = "steelblue") +
  geom_sf(data = md_bound, fill = "gray80", col = "gray75") +
  geom_sf(data = bmore_hv22, aes(fill = estimate), col = "transparent") +
  scale_fill_gradient(
    high = "orangered4",
    low = "lightgoldenrod1",
    labels = scales::dollar) +
  theme_void() +
  xlim(-76.75, -76.48) +
  ylim(39.2, 39.38) +
  theme(legend.position = "bottom", legend.key.width = unit(1.5, "cm")) +
  labs(fill = "Median Home Value",
       title = "2022 Median Home Value",
       subtitle = "Baltimore City, MD")

#2022 Median Rent

```


## Moving to Modelling
```{r modelling, warning=FALSE, message=FALSE}
p_load(stargazer)

all.acs12 <- all.acs %>%
  select(GEOID, gentrify, ends_with("12"))

train <- all.acs12 %>%
  sample_frac(.75)

train_index <- as.numeric(rownames(train))

test <- all.acs12[-train_index, ]

reg.gentrify <- glm(gentrify ~ ., data = 
                    train %>%
                      select(-GEOID),
                    family = "binomial"(link = "logit"))

stargazer(reg.gentrify, type = "text", out = "regression_summary.txt", title = "Regression Results", 
          label = "tab:regression_results", align = TRUE, 
          ci = TRUE, ci.level = 0.95, single.row = TRUE, 
          star.cutoffs = c(0.05, 0.01, 0.001), 
          notes = c("*** p<0.001", "** p<0.01", "* p<0.05"), 
          notes.align = "l", notes.label = "Significance levels:")
```

Testing the outcomes. 

```{r confusionmatrix, warning=FALSE, message=FALSE}
testProbs <- 
  data.frame(class = test$gentrify,
             probs = predict(reg.gentrify, test, type = "response"))

testProbs %>%
  mutate(predClass = ifelse(probs >= .5, "1", "0"), 
         predClass = factor(predClass, levels = c("0", "1")),  
         class = factor(class, levels = c("0", "1"))) %>% 
  { caret::confusionMatrix(.$predClass, .$class, positive = "1") }
```

More stuff

```{r probdist, warning=FALSE, message=FALSE}
p_load(ggplot2)
palette_4_colors <- c("#e4572e","#17bebb","#ffc914","#A379C9")
root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

ggplot(testProbs, aes(x = probs, fill = as.factor(class))) + 
  geom_density() +
  facet_grid(class ~ .) +
  scale_fill_manual(values = palette_4_colors) + xlim(0, 1) +
  labs(x = "Gentrify", y = "Density of probabilities",
       title = "Distribution of predicted probabilities by observed outcome") +
  plotTheme() + theme(strip.text.x = element_text(size = 18),
        legend.position = "none")+
  theme(text = element_text(family = "Times New Roman", size = 12), 
        plot.title = element_text(face = "bold", size = 14),
        plot.subtitle = element_text(size = 12),
        plot.caption = element_text(size = 8))
```

More of the stuff. This time calling up a ROC curve. 

```{r ROCcurve, warning=FALSE, message=FALSE}
p_load(pROC)

iterateThresholds <- function(data, observedClass, predictedProbs) {
  observedClass <- enquo(observedClass)
  predictedProbs <- enquo(predictedProbs)
  
  x <- 0.01
  all_prediction <- data.frame()
  
  while (x <= 1) {
    this_prediction <- data %>%
      mutate(predclass = ifelse(!!predictedProbs > x, 1, 0)) %>%
      count(predclass, !!observedClass) %>%
      summarize(
        Count_TN = sum(n[predclass == 0 & !!observedClass == 0]),
        Count_TP = sum(n[predclass == 1 & !!observedClass == 1]),
        Count_FN = sum(n[predclass == 0 & !!observedClass == 1]),
        Count_FP = sum(n[predclass == 1 & !!observedClass == 0]),
        Rate_TP = Count_TP / (Count_TP + Count_FN),
        Rate_FP = Count_FP / (Count_FP + Count_TN),
        Rate_FN = Count_FN / (Count_FN + Count_TP),
        Rate_TN = Count_TN / (Count_TN + Count_FP),
        Accuracy = (Count_TP + Count_TN) / (Count_TP + Count_TN + Count_FN + Count_FP),
        Threshold = round(x, 2),
        .groups = 'drop'
      )
    
    all_prediction <- rbind(all_prediction, this_prediction)
    x <- x + .01
  }
  
  return(all_prediction)
}

testProbs.thresholds <- iterateThresholds(
  data = testProbs, 
  observedClass = class, 
  predictedProbs = probs
)

ggplot(testProbs.thresholds, aes(x = Threshold)) +
  geom_line(aes(y = Accuracy, color = "Accuracy")) +
  geom_line(aes(y = Rate_TP, color = "True Positive Rate")) +
  geom_line(aes(y = Rate_FP, color = "False Positive Rate")) +
  scale_color_manual(values = c("Accuracy" = "blue", "True Positive Rate" = "green", "False Positive Rate" = "red")) +
  labs(title = "Model Performance Across Different Thresholds",
       x = "Threshold", y = "Rate") +
  theme_minimal() +
  theme(legend.title = element_blank(),
        legend.position = "bottom",
        text = element_text(family = "Times New Roman", size = 12),
        plot.title = element_text(face = "bold", size = 14),
        plot.subtitle = element_text(size = 12),
        plot.caption = element_text(size = 8))
```

ROC curve

```{r}
p_load(gridExtra)

aucTable <- testProbs %>% 
  summarize(AUC = as.numeric(auc(roc(class, probs)))) %>% 
  mutate(AUC = as.character(round(AUC, 3)))

mutate(testProbs.thresholds, pointSize = ifelse(Threshold == .48, 24, 16)) %>%
  ggplot(aes(Rate_FP, Rate_TP)) + 
  geom_point(aes(shape = pointSize)) + geom_line() + scale_shape_identity() +
  geom_abline(slope = 1, intercept = 0, size = 1.5, color = 'grey') +
  annotation_custom(tableGrob(aucTable, rows = NULL), xmin = .65, xmax = 1, ymin = 0, ymax = .45) +
  labs(title="ROC Curves", x="False Positive Rate", y="True Positive Rate") +
  plotTheme()+
  theme(text = element_text(family = "Times New Roman", size = 12), 
        plot.title = element_text(face = "bold", size = 14),
        plot.subtitle = element_text(size = 12),
        plot.caption = element_text(size = 8))
```


